### ISSUE TITLE
Adding tags

### ISSUE THREAD

**Issue by gg4u** [trevoreyre/autocomplete#101]
Hi Trevor!
congratulation for the well thought component! I have a question about how to adapt a single page vue for adding tags (here an example for jquery https://loopj.com/jquery-tokeninput/ )

I'd like to create a new tag on `handleSubmit(result)` and add the new tag on the input field (and so within the component). 

Could you describe a mockup to achieve that ? Or any plan to include it ?

**Comment by trevoreyre** [comment]
You would have to use [the default slot](https://autocomplete.trevoreyre.com/#/vue-component?id=default-slot) with your own custom input component that could display the tags. I'm afraid I don't have a good example of this readily available. It's not something that I'm planning on adding to the component at this point.

**Comment by gg4u** [comment]
ok, thank you for the indication. I will look at the default slot.

**Comment by gg4u** [comment]
ok, thank you for the indication. I will look at the default slot.

**Comment by trevoreyre** [comment]
I'm going to close this issue. Please feel free to reopen if you're still having issues.
