### ISSUE TITLE
use searched result in other components

### ISSUE THREAD

**Issue by smartgamer** [trevoreyre/autocomplete#104]
Hello, is it possible to use searched result in other components in vue js?

**Comment by trevoreyre** [comment]
I'm not completely sure what you mean. Could you give a more detailed example of what you're trying to accomplish.

One thing you could do - in the autocomplete `submit` event, save the selected result in your component data, or in a global store if you have one, and then other components could access that value.

**Comment by smartgamer** [comment]
Thank you. I think you answered my question.
________________________________

**Comment by trevoreyre** [comment]
Great! I'll go ahead and close then. Cheers.
