### ISSUE TITLE
Using with bootstrap-vue

### ISSUE THREAD

**Issue by davidebettio** [trevoreyre/autocomplete#110]
Hi,
how can I use a b-form-input style input inside the custom-input?

**Comment by trevoreyre** [comment]
You should be able to use the default slot for full control of rendering the component.

https://autocomplete.trevoreyre.com/#/vue-component?id=default-slot

**Comment by trevoreyre** [comment]
I'm going to go ahead and close this issue. Feel free to reopen if you need more help.
