### ISSUE TITLE
I have same page two autocomplete   

### ISSUE THREAD

**Issue by roborock** [trevoreyre/autocomplete#117]
I have same page two autocomplete    with choose radio button
but autocompletes are confusing why  ....
![img62](https://user-images.githubusercontent.com/24798675/101450360-80b2fe80-393b-11eb-93f9-7e8b51e277f9.png)

**Comment by trevoreyre** [comment]
Take a look at #26 for how to render multiple autocomplete components on the page.

https://github.com/trevoreyre/autocomplete/issues/26

Does that answer your question?

**Comment by trevoreyre** [comment]
I'm going to go ahead and close this issue. Feel free to reopen if you need more help.
