### ISSUE TITLE
Is it possible to search with two set of values?

### ISSUE THREAD

**Issue by xXxcb** [trevoreyre/autocomplete#119]
Basically I want to search by firstname and lastname. Is this possible?

```
search( input ) {
      if ( input.length < 2 ) { return [] }
      return this.candidates.filter( candidate => {
        if( candidate.firstname ) {
          return candidate.firstname.toLowerCase().startsWith(input.toLowerCase())
        }
      })
    },
```

**Comment by trevoreyre** [comment]
Definitely possible. Something like:

```js
search(input) {
  if (input.length < 2) { return [] }
  
  const inputLower = input.toLowerCase()
  return this.candidates.filter(candidate => {
    return (
      candidate.firstname?.toLowerCase().includes(inputLower) ||
      candidate.lastname?.toLowerCase().includes(inputLower)
    )
  })
}

```

**Comment by xXxcb** [comment]
Awesome! Thanks for your response. But I want to be able to search by first and last name or display the first names and last names when searching the 1st name only.

<img width="422" alt="Screenshot 2020-12-18 at 4 45 16 PM" src="https://user-images.githubusercontent.com/23020371/102664314-77523f00-4150-11eb-8048-2bb0009053d6.png">
