### ISSUE TITLE
sporadic loading in browser

### ISSUE THREAD

**Issue by sudhamsh-birudaraju-tfs** [trevoreyre/autocomplete#140]
First time, while loading the page, autocomplete css related is not loading.
when refresh the page or clear cache, after then, its loading properly. 
observed in chrome, edge browsers
how to load autocomplete along with css during first time.

**Comment by sudhamsh-birudaraju-tfs** [comment]
in chrome browser:
![image](https://user-images.githubusercontent.com/70195662/190157569-f8252cf6-9493-4763-9511-3b35d5ae9646.png)

in edge browser:
![image](https://user-images.githubusercontent.com/70195662/190157802-c0dd2fa1-1e93-44af-bed4-5dd89b06bebc.png)

**Comment by trevoreyre** [comment]
I can’t really help you with this issue. There are any number of reasons why your CSS might not be working on a page, depending how you’re including it on the page, what framework you’re using, etc.
