### ISSUE TITLE
link is broken.

### ISSUE THREAD

**Issue by JKwang00** [trevoreyre/autocomplete#141]
I use it.

<link rel='stylesheet' href='https://unpkg.com/@trevoreyre/autocomplete-js/dist/style.css'>
<script src='https://unpkg.com/@trevoreyre/autocomplete-js'></script>

link is broken.

I can't use npm so i used the browser bundle in a script tag.

can you restore it?

thank you.

**Comment by trevoreyre** [comment]
The unpkg link is working for me. Can you check again? There is no way to restore a link to unpkg. Those are all pulled automatically from npm.
