### ISSUE TITLE
search function asynchronous calls - debounce

### ISSUE THREAD

**Issue by majoksa** [trevoreyre/autocomplete#24]
I need to restrict API calls while writing suggestion. Can I fetch a call to debounce?

**Comment by trevoreyre** [comment]
There’s no option to denounce internally in the component. But I think it would work if you manually denounce your own search/fetch function so it doesn’t fire too often.

I’m guessing you might need to cache the most recent set of returned results to return from the search function in between calls to your API.

Have you had a chance to play around with this and get something working? I’m curious what you came up with.

**Comment by trevoreyre** [comment]
@majoksa I haven't heard anything in awhile. I'm going to go ahead and close this issue, feel free to re-open if you're still having issues.
