### ISSUE TITLE
How to use multiple autocomplete instances

### ISSUE THREAD

**Issue by ammonkc** [trevoreyre/autocomplete#26]
how can I have multiple instances at a time in a v-for loop. Is there a way to pass an index to the submit handler along with the result? I'm struggling to find a way to handle the submit event of dynamically added autocomplete instances.

For example: 
```
<div v-for="(airport, index) in airports">
    <autocomplete :search="airportAutocomplete" @submit="handleSubmit(result, index)"></autocomplete>
</div>

...

data() {
  return {
    airports: [
      {
        code: '',
      },
      {
          code: '',
      },
      {
        code: '',
      }
    ]
  }
},
methods: {
  handleSubmit(result, index) {
    this.airports[index].code = result.code
  }
}
```

**Comment by trevoreyre** [comment]
Yes, you can do that by passing a function to the submit event that returns the event handler function. The syntax to create a closure like that in Vue is a little trickier than normal, but here's the gist:

```
<autocomplete v-on=" { submit: handleSubmit(index) }"></autocomplete>
...
methods: {
  handleSubmit(index) {
    return result => {
      const airport = this.airports[index]
      console.log(result, airport.code)
    }
  }
}
...
```

[Here's a working Codesandbox to demonstrate](https://codesandbox.io/embed/trevoreyreautocomplete-vue-v-for-example-9ggxn).

**Comment by ammonkc** [comment]
Thanks @trevoreyre this is exactly what I was looking for! Really liking working with your autocomplete package. Thanks for your help!

Ammon
