### ISSUE TITLE
(Question) use without module bundler?

### ISSUE THREAD

**Issue by vitality82** [trevoreyre/autocomplete#31]
Hey Trevor,

In our project, we don't have support for Webpack, Node, ES6 modules (import/export).
I was able to integrate Vue but all my Vue components have separate Vue DOM templates. 

Your autocomplete-vue package provides a single file Vue component, so my question is: 
Should I use the javascript package and provide a Vue wrapper myself, or would you think it's easier to refactor you single file component into multiple files (js, html, css) ?

**Comment by trevoreyre** [comment]
You can use the browser bundle if you're not using webpack. You would add a script to your HTML template like this.

```html
<!-- Load the script from your server... -->
<script src="/path/to/@trevoreyre/autocomplete-vue/dist/autocomplete.min.js"></script>

<!-- ...or from unpkg -->
<script src="https://unpkg.com/@trevoreyre/autocomplete-vue"></script>
```

You can also include the CSS separately.

```html
<!-- From your server... -->
<link rel="stylesheet" href="/path/to/@trevoreyre/autocomplete-vue/dist/style.css">

<!-- ...or from unpkg -->
<link rel="stylesheet" href="https://unpkg.com/@trevoreyre/autocomplete-vue/dist/style.css">
```

If you look at some of the examples in [this autocomplete-vue Codepen collection](https://codepen.io/collection/nLLLyx/) they are all using the minified browser bundle with no webpack or build steps, and a regular HTML template.

Let me know if that answers your question. I'm not sure I completely understand what you mean about having separate Vue DOM templates and needing to create a Vue wrapper yourself. So if this isn't what you were asking, maybe you could clarify and provide a couple examples?

**Comment by vitality82** [comment]
My mistake @trevoreyre -  this answers my question.

I was initially searching for the /dist in this repo and thought I would need to use the .vue single file component, but I missed the fact I can download straight ahead from unpkg.

Thanks!

**Comment by trevoreyre** [comment]
No problem. The confusion is understandable. It probably wouldn't be a bad idea to include the `dist` folder in the repo. Right now if you wanted to self-host the minified JavaScript bundle you'd have to clone the repo and build it yourself, or copy it from unpkg or something.

Anyway, I'll go ahead and close this issue. Let me know if anything else comes up.
