### ISSUE TITLE
set the name attribute on input field

### ISSUE THREAD

**Issue by x1c0** [trevoreyre/autocomplete#39]
Hi there,

I'm trying to use this autocomplete vue in a traditional php form (laravel) and I need to setup the name of the input in order to the value to get passed to the form action.

There is any way of doing this? or maybe workaround? 

Thank you in advance!

**Comment by x1c0** [comment]
I could not find it on the documentation.. but just by setting `name` on `<autocomplete>` it works.. sorry for the open issue, closing it now :D

**Comment by trevoreyre** [comment]
There is a note in the docs in the props section, but I think you're right that it's very easy to miss.

https://autocomplete.trevoreyre.com/#/vue-component?id=props

> Note: Any extra props you pass will be spread on the input element of the autocomplete component.

I might try to make that note stand out more in the docs. Glad you got things figured out :)
