### ISSUE TITLE
Clearing result after submit

### ISSUE THREAD

**Issue by linuslabo** [trevoreyre/autocomplete#40]
I'm very new to Vue, and I cannot find a way to clear the autocomplete `value` after a submit request has been handled.
Any advice?

It would be a nice _Prop_ as well.

**Comment by trevoreyre** [comment]
You can use a ref for that. Take a look at the issue below.

https://github.com/trevoreyre/autocomplete/issues/25

**Comment by trevoreyre** [comment]
I'm going to go ahead and close this issue. Feel free to re-open if it's still not working for you.
