### ISSUE TITLE
Render button inline next to the autocomplete

### ISSUE THREAD

**Issue by vitality82** [trevoreyre/autocomplete#42]
Can you provide an example of how to render a button next to the autocomplete? This seems like an common UI pattern. 

I guess the root div wrapper cannot be inline-block correct?
![2019-10-07_15-10-55](https://user-images.githubusercontent.com/3256598/66315121-6f282e00-e915-11e9-915a-697ba85b6ec9.png)

I was able to modify the example with default slot (full control), but does one need to write all this in order to render an inline button?

![2019-10-07_15-23-21](https://user-images.githubusercontent.com/3256598/66315701-916e7b80-e916-11e9-8334-a4880ad8eb5c.png)

Is there an simpler approach?
For this so common use case, would you consider adding a slot for rendering some content directly after or directly before the input element?

**Comment by trevoreyre** [comment]
I agree using the default slot to put in a button seems like a lot of work for a simple use case. I think what I would probably do is wrap the entire component with a `div` or `form` element that could handle laying it out next to other elements.

Here's an example: https://codepen.io/trevoreyre/pen/RwwNKLK

**Comment by vitality82** [comment]
Thanks, That will work!
