### ISSUE TITLE
prevent default form submit using autocomplete

### ISSUE THREAD

**Issue by x1c0** [trevoreyre/autocomplete#45]
I have the following modified code from docs example: https://codepen.io/trevoreyre/pen/vbqpxv 

I just wrapped in in a form, since this are my requirements:
- typing for something in the input without selecting any option from dropdown performs a normal server search (GET)
- typing for something in the input, moving the key down (selecting one suggestion) and press ENTER -> go to the result page

```
<div id="app">
  <form action="www.test.com/search" method="GET">
    <autocomplete
      :search="search"
      placeholder="Search Wikipedia"
      aria-label="Search Wikipedia"
      :get-result-value="getResultValue"
      @submit="handleSubmit"
    ></autocomplete>
  </form>
</div>
```
my problem is that `handleSubmit` is called but the default `form` action is faster, causing the page to reload and do the server GET.

There is any way to preventDefault on the form? or another ideas?

Thank you!

**Comment by trevoreyre** [comment]
You could add a submit handler to the form element and `preventDefault` there.

```
<div id="app">
  <form @submit="handleFormSubmit">
    <autocomplete />
  </form>
</div>

// Script
{
  methods: {
    handleFormSubmit(event) {
      event.preventDefault()
      // Or whatever other logic you want to add to form submit
    }
  }
}
```

**Comment by x1c0** [comment]
Sure, but then if I really want to do a normal form submit for the /search action how can I do it? if I `preventDefault` then only the ` handleSubmit(result)` will be called, and I would like to distinguish between the 2 types of submit. not sure If i'm explaining myself properly =)

**Comment by trevoreyre** [comment]
Oh, I think I see what you mean. In my testing, the autocomplete submit event always fires before the form submit event, and it fires with `result === undefined` if you press enter in the input field without selecting a result from the list.

So maybe what you could do is set a variable in the autocomplete submit handler if `result !== undefined`, which would mean a result was selected from the list. Then in the form submit handler, check that variable, and only `preventDefault` if a specific result was selected. Is that what you're after?

Here's an example. Open up the console and compare the results when selecting a result vs just hitting enter in the input field. Also note that I haven't done extensive testing in different browsers.

https://codepen.io/trevoreyre/pen/RwwNKLK

**Comment by x1c0** [comment]
Thanks @trevoreyre I did similar to your approach and here is my solution:

```javascript
handleFormSubmit(event) {
    event.preventDefault();
    if (this.formToPost) {
        event.currentTarget.submit();
    }
},

handleSubmit(result) {
    if (!result) {
        // user did not select an option from dropdown
        this.formToPost = true;
    } else {
        this.formToPost = false;
        // navigate to product page
        window.location.href = `/products/${encodeURI(result.id)}`;
    }
},
```

**Comment by allesan** [comment]
I have the same situation, but with JavaScript component.
How can I do resolve this with JavaScript component?

**Comment by trevoreyre** [comment]
@allesan You should be able to do pretty much the same setup with the JavaScript component. Is it not working for you?

**Comment by allesan** [comment]
Yeah, after I posted this I got eureka moment and solved it in a similar manner :+1: 
Thanks, although it would be good to add official example to the docs in the future.

**Comment by tsrivishnu** [comment]
For the Javascript component, I needed something that is more generic for all the instances of Autocomplete. So, I created an wrapper class and set a new `keydown` event listener that prevents default.

```javascript
class SkillAutocomplete {
  constructor(containerElem, { onSubmit = () => {} } = {}) {
    let autocomplete = new Autocomplete(containerElem, {
      ...
    });

    autocomplete.input.addEventListener('keydown', (event) => {
      const { key } = event
      if (key == 'Enter') {
        event.preventDefault();
      }
    });
  }
}
```

**Comment by mila76** [comment]
@trevoreyre I think is really useful have access to the event on onSubmit in a  second parameter so is easy to stop the event
