### ISSUE TITLE
Vue - accessing DOM nodes within Vue methods

### ISSUE THREAD

**Issue by tamb** [trevoreyre/autocomplete#49]
methods like `search` `onSubmit` should pass in the root node of the component or the input component.  When dynamically creating autocompletes, this reference may be necessary.  

Also, please create a `Core` `Vue` label for issues and maybe even a `v2-patch` and `v3` label

**Comment by trevoreyre** [comment]
I added `core`, `vue`, and `js` labels, and updated all open issues. I already have a `v3` milestone that I've added most of the issues to.

As to your request that `search` and `onSubmit` should pass the root node of the component. I'm not sure I totally understand. Could you possibly give a more concrete example of when you would need this and how you would expect to use it?

**Comment by trevoreyre** [comment]
@tamb I never heard back about your original suggestion for accessing DOM nodes. I'm going to close this issue. Feel free to re-open if you have more information.
