### ISSUE TITLE
Deferred component creation

### ISSUE THREAD

**Issue by NesCafe62** [trevoreyre/autocomplete#50]
I tired to use same method I use for some of my components:

```js
import Autocomplete from '@trevoreyre/autocomplete-vue';
function createAutocomplete(el, options) { // el is just empty div
	let component = new Autocomplete({
		propsData: options
	});
	component.$mount(el);
	return component;
}
```

But have an error: "TypeError: __WEBPACK_IMPORTED_MODULE_1__trevoreyre_autocomplete_vue__.a is not a constructor".

Is there a way to create component dynamically (by demand) and mount to DOM element? It's preferable to have it as root Vue instance.

**Comment by trevoreyre** [comment]
Do you have an example of another component you use this way? Or a link to some docs about this method of instantiating a component? I'm afraid I'm not familiar with this way of consuming a Vue component, so I might have done something wrong that doesn't support it correctly.

**Comment by NesCafe62** [comment]
I used this article https://css-tricks.com/creating-vue-js-component-instances-programmatically/ and other sources (don't remember them yet). I made a mistake forgot to use `Vue.extend`:

```js
import Autocomplete from '@trevoreyre/autocomplete-vue';
const AutocompleteConstructor = Vue.extend(Autocomplete);
function createAutocomplete(el, options) {
	let component = new AutocompleteConstructor({
		propsData: options
	});
	component.$mount(el);
	return component;
}
```

But it's still not working.

Another component I use this way is simple single file vue component "ModalDialog.vue":

```js
<template>
    <!-- here is template -->
</template>

<script>
export default {
    name: 'ModalDialog',
    props: { /* ... */ },
    data() {
        return { /* ... */ }
    },
    methods: { /* ... */ }
}
</script>
```

Usage of that:

```js
import ModalDialog from 'components/ModalDialog';
const ModalDialogConstructor = Vue.extend(ModalDialog);
function createModalDialog(el, options) {
	let instance = new ModalDialogConstructor({
		propsData: options
	});
	instance.$mount(el);
	return instance;
}
```

**Comment by trevoreyre** [comment]
Ah, okay. Everything is working for you now, then? I’ll go ahead and close the issue then. Feel free to re-open if I’m still missing something.
