### ISSUE TITLE
Add the capacity to format result

### ISSUE THREAD

**Issue by augnustin** [trevoreyre/autocomplete#56]
It seems like `getResultValue` **must** return a string, while it could be interesting that it is able to return HTML to allow subformatting (eg. highlighting).

I guess this should be optionable, but for instance there could be another attribute `    :get-result-value-html="getResultValue"` which would `<span v-html="getResultValueHtml(result)"></span>` instead of `{{getResultValue(result)}}`.

The best solution would be to being able to return a component, but I have the impression that it is not possible with vue, is it?

**Comment by trevoreyre** [comment]
You can use the [result slot](https://autocomplete.trevoreyre.com/#/vue-component?id=result) to fully customize the HTML of a result, or the [default slot](https://autocomplete.trevoreyre.com/#/vue-component?id=default-slot) to fully customize the HTML of the entire component.

**Comment by trevoreyre** [comment]
I'm going to close this issue if those slot options work for you. Feel free to re-open if you're still having issues.

**Comment by augnustin** [comment]
Great, this is exactly what I needed! :smile: 
Thanks

**Comment by allesan** [comment]
Is this possible for pure JS component?

**Comment by trevoreyre** [comment]
Yes, you can use the renderResult option in the JS component.

https://autocomplete.trevoreyre.com/#/javascript-component?id=renderresult
