### ISSUE TITLE
clearing selected value

### ISSUE THREAD

**Issue by ashikvs** [trevoreyre/autocomplete#64]
I couldn't find an option to clear the selected value in the input, can any one guide me on doing the same?

**Comment by trevoreyre** [comment]
You should be able to add a ref to the component and then clear it using the ref. That'll look something like this:

```
<Autocomplete ref="autocomplete" />
```

```
this.$refs.autocomplete.value = ''
```

Please give that a try and let me know if it works out.

**Comment by ashikvs** [comment]
thanks a lot!! @trevoreyre it would be nice if you could include that in the documentation, i was trying out the Vue component and couldn't find it.

**Comment by mirzaakhena** [comment]
in vue3 (with composition-api) it would be like this

```
<template>

...

<Autocomplete ref="autocomplete" />

...

</template>
```

```
<script setup>

...

// define it
const autocomplete = ref(null)

// call it under some method
const clearTheAutoComplete = () => {
  autocomplete.value.setValue('')
}

...

</script>

```
