### ISSUE TITLE
Not rendering and getting `this.$refs.root is undefined` error

### ISSUE THREAD

**Issue by andrewtweber** [trevoreyre/autocomplete#68]
I've tried both importing the Vue component, and just linking to the browser bundle. Either way I get the same issue

The component simply renders as `<!---->` and nothing is displayed at all.

And clicking anywhere on the page gives a console error from the `handleDocumentClick` method

```
TypeError: this.$refs.root is undefined
```

**Comment by trevoreyre** [comment]
@andrewtweber I haven't seen that happen before. Any way you can provide a repo or CodeSandbox to reproduce?

**Comment by andrewtweber** [comment]
I ended up using a different package. Probably user error, forget it
