### ISSUE TITLE
Onblur execute function

### ISSUE THREAD

**Issue by robersonfaria** [trevoreyre/autocomplete#7]
Hello, I really liked the vuejs component, however I can not get the onblur to trigger an event/function like the onsubmit.
Is there any way in onblur to run the onsubmit or the same function set for it?

**Comment by trevoreyre** [comment]
You're right. I don't have regular event handlers being forwarded on to the input element currently, so there's no way to trigger a submit on blur. I'll try to get a PR up for this early next week.

**Comment by trevoreyre** [comment]
@robersonfaria This should work now in v1.0.2. Here's an example of how you can call the onSubmit function from a blur event handler:

https://codepen.io/trevoreyre/pen/KYJwPa

You may have to do some debouncing yourself to make sure onSubmit isn't being fired multiple times (if that matters in your case). For example, when a user clicks a result in the results list, it would fire the onSubmit prop, and then fire the blur event when the input is blurred.

**Comment by robersonfaria** [comment]
@trevoreyre thank you, it worked.

**Comment by tamb** [comment]
> @robersonfaria This should work now in v1.0.2. Here's an example of how you can call the onSubmit function from a blur event handler:
> 
> https://codepen.io/trevoreyre/pen/KYJwPa
> 
> You may have to do some debouncing yourself to make sure onSubmit isn't being fired multiple times (if that matters in your case). For example, when a user clicks a result in the results list, it would fire the onSubmit prop, and then fire the blur event when the input is blurred.

This example doesn't work if you're working with an array of objects because onSubmit doesn't handle the event it handles a value of getResultValue prop.  However, on blur I need the entire object and not just the event or the value of the input.
