### ISSUE TITLE
Sens custom HTML to response

### ISSUE THREAD

**Issue by Siopyy** [trevoreyre/autocomplete#73]
Hello,

is it possible to send html in response? If yes, how ? 

Thanks

**Comment by trevoreyre** [comment]
I'm not sure I completely understand your question. But if you want to use custom HTML in the list of results displayed in the component, you can use the [result slot](https://autocomplete.trevoreyre.com/#/vue-component?id=result) if you're using the Vue component, or the [renderResult function](https://autocomplete.trevoreyre.com/#/javascript-component?id=renderresult) if you're using the JavaScript component.

**Comment by trevoreyre** [comment]
@Siopyy I haven't heard back, so I'm going to close this issue. Feel free to re-open if you're still having issues.
