### ISSUE TITLE
How to clear/reset the autocomplete?

### ISSUE THREAD

**Issue by MBurchard** [trevoreyre/autocomplete#74]
I'm using Autocomplete from '@trevoreyre/autocomplete-vue' with version 2.1.0.

In my Vue component, I search for a user, then change same values and submit the changed user to the backend. If this succeeds I want to reset all input fields, including the autocomplete. How can this be done in a way, that also the internal state of autocomplete is empty...

**Comment by trevoreyre** [comment]
Does #64 cover your use case? Or is there more internal state that you need to clear out? Could you provide a little more detail about what you're trying to achieve?

**Comment by MBurchard** [comment]
Thank you, works as expected...
