### ISSUE TITLE
How to modify the script to add required & placeholder atributes

### ISSUE THREAD

**Issue by abaar** [trevoreyre/autocomplete#76]
I'm newb, and i added some codes to your code for vue component, succeed adding placeholder atributes, but not with the required. How do i add that required feature? Thanks

**Comment by trevoreyre** [comment]
I'm not sure I understand. Any extra attributes you pass to the Autocomplete component should be passed on to the input element. So if you do something like this:

```
<Autocomplete placeholder="Placeholder" required :search="searchFn" />
```

If should add the placeholder and required attributes to the input. Is that not working for you? And if so, can you please provide an example of what you're trying to accomplish?

**Comment by trevoreyre** [comment]
I never heard back, so I'm going to close this issue. Feel free to re-open if you're still having issues.
