### ISSUE TITLE
Results being displayed even if the search term is null

### ISSUE THREAD

**Issue by AdrienPoupa** [trevoreyre/autocomplete#79]
Hello,

First of all thanks for your component it is working great for me!

I have a small problem related to an edgy use case I have; I need to clear the input and its results and then focus to the input programmatically.

I am using Vue. I managed to do it with 
```js
this.$refs.autocomplete.value = '';
this.showResults = false;
this.$refs.autocomplete.$el.firstElementChild.children[0].focus();
```

I think when I focus it is triggering a search because sometimes it will show me results from what used to be the value.

This is what I mean: you can see the old result while the input is empty:

![image](https://user-images.githubusercontent.com/15086425/78954492-5f4afb80-7aaa-11ea-821b-e69f81b0d7bf.png)

I also use an async answer coming from axios if it helps.

I think it is related to this: https://github.com/trevoreyre/autocomplete/issues/15 "Autocomplete executes the search function on focus". I really wish I could disable this somehow.

My hacky approach that does not seem to always work is to have a `showResults` boolean in my Vue data, setting it to false before focusing and doing this in my search function:

```js
            search: function(input) {
                if (input === '') {
                    return [];
                }

                return axios.get(...))
                    .then(response => {
                        if (! this.showResults) {
                            this.showResults = true;
                            return [];
                        }

                        return response.data;
                    });
            },
```

**Comment by AdrienPoupa** [comment]
So I think this may have to do with the fact that the axios request completes after the value is reset to ''.

I was able to fix this by taking control of the template like this:

```js
                            <template
                                #default="{
                                rootProps,
                                inputProps,
                                inputListeners,
                                resultListProps,
                                resultListListeners,
                                results,
                                resultProps
                              }">
                                <input
                                    style="padding: 24px 24px 24px 48px"
                                    v-bind="inputProps"
                                    v-model="serialNumberAutocomplete"
                                    v-on="inputListeners"
                                    ref="autocompleteSerialNumberInput"
                                    class="autocomplete-input form-control"
                                    @blur="autocompleteSerialNumberBlur"
                                />
                                <div v-bind="rootProps">
                                    <ul v-bind="resultListProps" v-on="resultListListeners" v-show="serialNumberAutocomplete !== ''">
                                        <li
                                            v-for="(result, index) in results"
                                            :key="resultProps[index].id"
                                            v-bind="resultProps[index]"
                                        >
                                            {{ result.id }}
                                        </li>
                                    </ul>
                                </div>
                            </template>
```

Notice the `v-show="serialNumberAutocomplete !== ''`, basically only display the results if the input is not empty.

So why is there a reason why this is not the case out of the box? It seems to make sense not to display results if the value is empty.

**Comment by trevoreyre** [comment]
It does seem like something odd is going on in your use case. If you clear the input value with a ref, you shouldn't be seeing previous results the next time it is focused.

It may have to do with your asynchronous search function. If `input === ''` you immediately return `[]`, but if not, you're returning a `Promise` by returning the `axios.get` call. Instead, you should _always_ be returning a promise, and just immediately resolving that promise with an empty array if `input === ''`.

You can do this by explicitly returning a `new Promise` in your search function, like in [this advanced search example](https://codepen.io/trevoreyre/pen/vbqpxv), or you could mark your search function as `async`.

**Comment by AdrienPoupa** [comment]
Thanks for your answer.

I tried with the following but it did not change anything:

```js
            autocompleteSerialNumber(input) {
                return new Promise(resolve => {
                    if (input === '') {
                        return resolve([])
                    }

                    axios.get(route('api.firearm.find-by-keyword', {assignmentType: this.assignmentType, text: input}))
                        .then(response => {
                            resolve(response.data);
                        });
                });
            },
```

**Comment by AdrienPoupa** [comment]
Thanks for your answer.

I tried with the following but it did not change anything:

```js
            autocompleteSerialNumber(input) {
                return new Promise(resolve => {
                    if (input === '') {
                        return resolve([])
                    }

                    axios.get(myUrl)
                        .then(response => {
                            resolve(response.data);
                        });
                });
            },
```

**Comment by trevoreyre** [comment]
Oh, I think I get it now. The problem happens when your axios request resolves after the input has already been cleared? I think you could get around that by checking if the input has any value before resolving the promise. Take a look at this example and let me know if that works for your use case.

https://codepen.io/trevoreyre/pen/YzyXRJN

**Comment by AdrienPoupa** [comment]
Just tried it (many thanks!) but it still does not work.

I was able to reproduce the issue consistently with this code: https://codepen.io/ldakdsa/pen/MWawLEv

Type anything, then press clear, and wait. You will see the results being displayed even if the input is null

**Comment by trevoreyre** [comment]
You're checking `this.value` and then firing a new promise with `setTimeout`. If you move it so you check `this.value` immediately at the point where you're resolving the promise, it works as intended.

https://codepen.io/trevoreyre/pen/vYNObzo

**Comment by AdrienPoupa** [comment]
You are right, your example works.

This showed me that I have another issue that I will debug later related to my blur function.

When I blur, I POST the autocomplete field to validate the value, and I reset the value to null if it is invalid. I guess this somehow interferes with the rest and shows the old results.

Many thanks for your help.
