### ISSUE TITLE
Add image to suggestions?

### ISSUE THREAD

**Issue by f-arthr** [trevoreyre/autocomplete#83]
I'm making a RSS aggregator and to add feeds, I use Autocomplete. I'd like to add the icon of the feeds in the suggestions of the search.

How can I do it?

(I import Autocomplete with a CDN.)

**Comment by trevoreyre** [comment]
If you're using the Vue component, you can use the [result slot](https://autocomplete.trevoreyre.com/#/vue-component?id=result), or if you're using the JavaScript component, you can use the [renderResult option](https://autocomplete.trevoreyre.com/#/javascript-component?id=renderresult).

Let me know if that works for you, and feel free to re-open the issue if you're having problems.

**Comment by f-arthr** [comment]
It works! Thanks 🙏
Here is my code added to the JS Component if someone want it:
```js
renderResult: (result, props) => `
    <li ${props} style="background-image: url('${result.iconUrl}')">
      <div class="title">
        ${result.title}
      </div>
    </li>
  `
```
