### ISSUE TITLE
Special Character Bug

### ISSUE THREAD

**Issue by cagandev** [trevoreyre/autocomplete#84]
Sharp (#) character is not working in fetching
Bug Screenshot: 
![image](https://user-images.githubusercontent.com/18090907/82371507-ff3d6280-9a22-11ea-870a-0883df8800e6.png)

**Comment by trevoreyre** [comment]
I think the browser is just interpreting the `#` as a [location hash](https://developer.mozilla.org/en-US/docs/Web/API/Location/hash) since it's at the end of the URL. This isn't a bug in the autocomplete component itself.
