### ISSUE TITLE
Autocomplete not reactive warning with nuxt

### ISSUE THREAD

**Issue by TooColline** [trevoreyre/autocomplete#87]
I keep getting this warning: 
```[Vue warn]: Property or method "autocomplete" is not defined on the instance but referenced during render```

Can't figure out why yet it's a component

**Comment by trevoreyre** [comment]
I've used the component with nuxt and haven't seen that warning before. You're sure that you're not trying to reference a prop or something that's defined in the wrong place, [like in this article](https://michaelnthiessen.com/property-or-method-not-defined/)?

If there's any way you can reproduce this warning in a CodeSandbox or a small GitHub repo, I might be able to help dig into what's going on.

**Comment by TooColline** [comment]
This was some other property. All good, thanks.
