### ISSUE TITLE
Validation error: Attribute autocorrect not allowed on element input at this point.

### ISSUE THREAD

**Issue by jenemde** [trevoreyre/autocomplete#88]
Using your nice autocomplete library (vue component), I receive an error when validating the code with w3c validator (https://validator.w3.org/nu/)  and also with the bookmarklet "Check serialized DOM of current page" (from https://validator.w3.org/nu/about.html).

The main problem is that the site should be accessible by means of WCAG and one of the steps to check is "no validation error". If this step is not passed the whole test for accessibility fails.

Could you remove the inputProp or make its apperance selectable (via props)?

**Comment by trevoreyre** [comment]
Can you provide a summary or screenshot of the errors being reported by the validator?

**Comment by jenemde** [comment]
Thanks for your fast answer. I've attached a screenshot.
![validator_w3_org_autocorrect](https://user-images.githubusercontent.com/53625399/85519210-70170200-b601-11ea-96e0-ef7760b2bc67.png)

**Comment by trevoreyre** [comment]
I see. I think `autocorrect` is a non-standard attribute on the input element, but it's required to disable auto correct on certain mobile browsers.

One option if you need to get around this is to use the [default slot](https://autocomplete.trevoreyre.com/#/vue-component?id=default-slot). That attribute will be present in `inputProps`, but you can filter it out before binding it to your input element in your template.

**Comment by jenemde** [comment]
Wow, I hadn't noticed the default slot.
After trying what you told me, I finally noticed
```...this.$attrs,```
in the computed property "inputProps".
So I added
```:autocorrect="null"```
to
```
             <auto-complete
                :id="`search-term-${randomStr}`"
                :placeholder="$t('search.placeholder')"
                :autocorrect="null"
                :search="queryAutoCompleteEntries"
            />
```
and the autocorrect attribute disappeared from the DOM - no more validation error.

Thanks a lot for your help and the nice contact.

**Comment by trevoreyre** [comment]
Oh yes, that's an even easier solution. Any extra props/attributes you provide will be applied to the input element. Glad it's working out for you. I'll go ahead and close this, but feel free to re-open if there's still any issue.
