### ISSUE TITLE
Vue: How to use button(remove) in autocomplete-result-list

### ISSUE THREAD

**Issue by sonnv25** [trevoreyre/autocomplete#90]
Hi!
How to click button to remove item in 'autocomplete-result-list'
Thanks!!

![Untitled](https://user-images.githubusercontent.com/23501072/85371833-1cea7400-b55b-11ea-8c24-08759b7d3810.png)

**Comment by trevoreyre** [comment]
I think the only way to do that would be to use the [default slot](https://autocomplete.trevoreyre.com/#/vue-component?id=default-slot) and take full control of the rendered output. You'd probably have to store the results that have been removed and conditionally filter those out of your result list based on that. It's a bit hacky, but it should be doable.

**Comment by trevoreyre** [comment]
I haven't heard back, so I'm going to go ahead and close this issue. Feel free to reopen if you're still having issues.
