### ISSUE TITLE
Display a label but set value to some id

### ISSUE THREAD

**Issue by lolobosse** [trevoreyre/autocomplete#91]
Hi there, 

First, thanks for the lib, you rock! :guitar: 

I have an issue which I didn't find in the other issues. I use no post processing for the form and I need to have my `name` and `value` field with the "final" values.

However, I have such data:

`[{id: 123, label:"Option 1"}]`

And you can imagine, I need to display `Option 1` but I want to send `123` to the server.

How am I supposed to achieve that if `v-model` is not working? Should I use events and write the values in a non visible field or is there a more elegant solution?

**Comment by trevoreyre** [comment]
You should be able to use either the [getResultValue prop](https://autocomplete.trevoreyre.com/#/vue-component?id=getresultvalue), or the [result slot](https://autocomplete.trevoreyre.com/#/vue-component?id=result).

**Comment by trevoreyre** [comment]
I haven't heard back, so I'm going to assume this issue is resolved. Feel free to reopen if you're still having issues. 👍
